### ISSUE TITLE
Email - high importance

### ISSUE THREAD

**Issue by marekk1717** [nylas/exchangelib#40]
Do you know to to set high importance flag on email message?

**Comment by stvnkem** [comment]
Hello,

I was looking for the same. Here is an example:
Valid choices are: High, Low, Normal
```
importance = 'High'
from exchangelib import Message
m = Message(account=account,
        folder=account.sent,
        subject=subject,
        body=body,
        to_recipients=to_recipients,
        importance=importance)
```

References:
https://ecederstrand.github.io/exchangelib/exchangelib/#exchangelib.Message
https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/message-ex15websvcsotherref

**Comment by yusra-ahmed-zz** [comment]
Hi @marekk1717,

This is a fork of https://github.com/ecederstrand/exchangelib. Issues should be raised there instead. Thanks!
