### ISSUE TITLE
mime content appears to be invalid base64 and cannot be decoded

### ISSUE THREAD

**Issue by schmidlidev** [nylas/exchangelib#43]
When trying to retrieve a large email (>2MB pure text) I get the following error.

`Cannot convert value [very long base64 string] on field 'mime_content' to type <class 'str'>`

This looks quite similar to some others have previously had:
https://github.com/ecederstrand/exchangelib/issues/584 
https://github.com/ecederstrand/exchangelib/issues/683

I looked at the actual '\<MimeContent CharacterSet="UTF-8">' field and it appears that Exchange is actually sending an impossible base64 encoding. The string is padded with '==' but 15310599 characters in total (including that padding). It is my understanding that the total number of characters must always be divisible by 4.

Passing the string directly into Python's base64.b64decode() function gives the following error:

`binascii.Error: Invalid base64-encoded string: number of data characters (15310597) cannot be 1 more than a multiple of 4`

Because of this, regardless of how many '=' padding characters appended to the end of the string, it will never successfully decode.

**Comment by yusra-ahmed-zz** [comment]
Hi @schmidlidev,

This is a fork of https://github.com/ecederstrand/exchangelib. Issues should be raised there instead. Thanks!
