### ISSUE TITLE
Acceptable kwargs for inbox.filter()

### ISSUE THREAD

**Issue by connorferster** [nylas/exchangelib#44]
I am looking for the complete list of acceptable kwargs that can be used with `.filter()`. I have read on the documentation, under **Searching**, that the kwarg can be used in conjunction with `__` in addition to various modifiers such as `exact`, `iexact`, and `contains`, etc. However, I am wondering what the list of "base" fields are (like, `sender` and `subject`) that can be used.

For example, in the documentation, there is a reference to the kwargs `subject` and `sender`, such as:  `.filter(subject = "My subject")` and `.filter(sender = "sender@sending.com")`. However, when I tried using a kwarg like `recipient`, `recipients`, or `to` I get an `InvalidField` error.

I of course read the Microsoft reference you posted (https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/querystring-querystringtype) and will just resort to using query strings if I have to but I am wondering if it is possible to get a list of the full set of "base" fields that are acceptable in `.filter()`. I have tried looking in `restrictions.py` and `fields.py` and `query_set.py` but I have not been able to find those references to the kwargs that I know will work: `sender` and `subject`. Could it be that these are the only two?

If you are able to point me to the list, I would be happy to update the documentation to include them. 

Many thanks! Exchangelib is an excellent library. I have enjoyed using it at my work: it's a real time saver.

**Comment by jhatch28** [comment]
Hey @connorferster, this is actually just a fork of https://github.com/ecederstrand/exchangelib. You might have better luck raising this question on that repo, as we're only experts on our particular use cases of the library.

**Comment by connorferster** [comment]
Oops! Thanks.
