### ISSUE TITLE
account.export() base64

### ISSUE THREAD

**Issue by martie1982** [nylas/exchangelib#46]
when trying to export all items in inbox i get the following error:

line 87, in b64decode
return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (81629965) cannot be 1 more than a multiple of 4.

below portion of code

items = account1.inbox.all().order_by('-datetime_received')
data = account1.export(items)

if i limit the amount of messages by changing code to
 items = account1.inbox.all().order_by('-datetime_received')[:100]
it completes without any issues

**Comment by yusra-ahmed-zz** [comment]
Hi @warmunger,

This is a fork of https://github.com/ecederstrand/exchangelib. Issues should be raised there instead.
